### ISSUE TITLE
Create database structure

### ISSUE THREAD

**Issue by ischeuermann** [EPinnick/Project-15-04#10]

**Comment by MitchSiegel** [comment]
Here's what I thinking for users table:
username (unique)
password (hashed)

movies table:
title
description 
release date 
poster image

review table:
number of stars (out of 6.5)
text (optional)

reviews to movies 
reviewId (from review table)
movieId (from movies table)

**Comment by ischeuermann** [comment]
Add SERIAL movie_id and review_id columns to the movies table and review table that CASCADE and create the reviews to movies

Add text column to review table that stores username
